version: '3.9'
services:
  database:
    image: postgres:14.2
    restart: on-failure
    environment:
      POSTGRES_DB: app
      POSTGRES_USER: app
      POSTGRES_PASSWORD: app
      POSTGRES_SERVER: database
    ports:
      - "5432:5432"
  app:
    build: .
    depends_on:
      - database
    ports:
      - "80:80"